entity: optimus-bits
project: phylolearn-dl4phylo
name: typing/original/random/1


method: random


metric:
    name: train/epoch-loss
    goal: minimize


parameters:

    seed:
        value: 42

    dataset:
        value: datasets/typing_data/original
    epochs:
        values: [40, 80, 120, 160]
    batch_size:
        values: [4, 8, 16, 32, 64]
    train_fraction:
        values: [0.9, 0.95]
    
    optimizer:
        values: [Adam, AdamW, SGD]
    learning_rate:
        distribution: uniform
        min: 0.0001
        max: 0.01
    
    criterion:
        values: [L1, L2]
    
    n_blocks:
        values: [6, 7, 8, 9, 10]
    n_heads:
        values: [4, 8, 16]
    h_dim:
        values: [32, 64, 128]
    dropout:
        values: [0.0, 0.2, 0.5]
    
    checkpoint:
        value: null
    
    amp:
        value: True
    clip_gradients:
        value: True
    early_stopping:
        value: False
    stopping_steps:
        value: null
    
    train_batch_logs_per_epoch:
        value: 0.01
    validation_batch_logs_per_epoch:
        value: 0.02
