entity: optimus-bits
project: dl4phylo
name: 10k-20-20-un-un-seqgen-f84-700000-1000-600-100/bayes/1


method: bayes


metric:
    name: train/epoch-loss
    goal: minimize


parameters:

    seed:
        value: 42

    dataset:
        value: typing_data/10k-20-20-un-un-seqgen-f84-700000-1000-600-100
    epochs:
        values: [40, 80, 120, 160, 180, 200]
    batch_size:
        values: [4, 8, 16, 32]
    train_fraction:
        values: [0.9, 0.95]
    
    optimizer:
        values: [Adam, AdamW, SGD]
    learning_rate:
        distribution: uniform
        min: 0.0001
        max: 0.1
    
    criterion:
        values: [L1, L2]
    
    n_blocks:
        values: [6, 7, 8, 9, 10]
    n_heads:
        values: [4, 8, 16]
    h_dim:
        values: [32, 64, 128]
    dropout:
        values: [0.0, 0.2, 0.5]
    
    checkpoint:
        value: null
    
    amp:
        value: True
    clip_gradients:
        value: True
    early_stopping:
        value: True
    stopping_steps:
        value: 8
    
    train_batch_logs_per_epoch:
        value: 0.01
    validation_batch_logs_per_epoch:
        value: 0.02
